fix: add binary existence check before running tests

diff --git a/.github/workflows/pr-check-server.yml b/.github/workflows/pr-check-server.yml
--- a/.github/workflows/pr-check-server.yml
+++ b/.github/workflows/pr-check-server.yml
@@ -40,8 +40,15 @@ jobs:
       - name: Build
         run: go build ./...
 
+      - name: Check if binary was built
+        run: |
+          if [ ! -f "server" ]; then
+            echo "Binary not found!"
+            exit 1
+          fi
+
       - name: Test
-        run: go test ./... $$(go list ./... | grep -v /cmd/)
+        run: go test $$(go list ./... | grep -v /cmd/)
 
       - name: Test Race
-        run: go test --race ./... $$(go list ./... | grep -v /cmd/)
+        run: go test --race $$(go list ./... | grep -v /cmd/)
